**[Numpy](https://numpy.org)**
* Linear algebra for dense vectors and matricies
* Convinient for images representing as numbers
* Implemented on C
* Pandas is based on numpy library

[official tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [1]:
import numpy as np

# Why you should consider use numpy in your back-end?

In [2]:
N = 10
arr1 = list(range(N))
arr2 = list(range(N))

def _dot(arr1, arr2):
    assert len(arr1) == len(arr2)
    return sum([arr1[i]*arr2[i] for i in range(len(arr1))])

In [3]:
%%timeit
_dot(arr1, arr2)

1.45 µs ± 32.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
%%timeit
arr3 = np.arange(N)
arr4 = np.arange(N)
arr3.dot(arr4)

1.75 µs ± 34.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
N = 1_000_000
arr1 = list(range(N))
arr2 = list(range(N))

arr3 = np.arange(N)
arr4 = np.arange(N)

In [6]:
%%timeit
_dot(arr1, arr2)

109 ms ± 5.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%%timeit
arr3.dot(arr4)

1.12 ms ± 92.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Arrays

## Array of integers

In [8]:
row_vec_int = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
row_vec_int, row_vec_int.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

## Array of floats

In [10]:
row_vec_float = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
row_vec_float, row_vec_float.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [12]:
row_vec_float.astype(np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [13]:
row_vec_float.shape

(9,)

## Array of strings

In [14]:
row_vec_str = np.array(list('Hello World!'))

In [15]:
row_vec_str

array(['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!'],
      dtype='<U1')

In [16]:
row_vec_str.shape

(12,)

## Indexing / Slicing

### Access by element index

`array[i]`, `array[[0, ..., n]]`,

`i` - intergers from `0` to `len(array) - 1`. Could be negative, starting from `-1` to `0`

In [17]:
row_vec_int

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
row_vec_int[0], row_vec_int[1]

(1, 2)

In [19]:
row_vec_int[-1], row_vec_int[-2]

(9, 8)

In [20]:
row_vec_int[[0, 4, 7, len(row_vec_int)-1]]

array([1, 5, 8, 9])

In [21]:
row_vec_int[[0, -5, -2, -1]]

array([1, 5, 8, 9])

### Slicing

For numpy arrays it's like for python `list`.

`array[start_idx: stop_idx: step]`

`start_idx, stop_idx, step` - integers (index of element). `start_idx` inclusive, `stop_idx` exlusive. Could be negative.

In [22]:
row_vec_int

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
row_vec_int[0: 5]

array([1, 2, 3, 4, 5])

In [24]:
row_vec_int[2: 5]

array([3, 4, 5])

In [25]:
row_vec_int[3:]

array([4, 5, 6, 7, 8, 9])

In [26]:
row_vec_int[1: len(row_vec_int): 2]

array([2, 4, 6, 8])

In [27]:
row_vec_int[1::2]

array([2, 4, 6, 8])

In [28]:
row_vec_int[0: len(row_vec_int): 2]

array([1, 3, 5, 7, 9])

In [29]:
row_vec_int[0::2]

array([1, 3, 5, 7, 9])

In [30]:
row_vec_int

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
row_vec_int[-1: 0: -2]

array([9, 7, 5, 3])

## Column array

In [32]:
col_vec = np.array([1, 2, 3, 4, 5])

In [33]:
col_vec, col_vec.shape

(array([1, 2, 3, 4, 5]), (5,))

In [34]:
col_vec.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [35]:
col_vec[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [36]:
col_vec[:, np.newaxis].shape

(5, 1)

In [37]:
col_vec[:, np.newaxis].shape

(5, 1)

## Creating arrays

### Empty array

In [38]:
vec_empty = np.empty((5,), dtype=np.float32)

In [39]:
vec_empty

array([-5.4070067e+09,  3.0967295e-41,  0.0000000e+00,  0.0000000e+00,
        4.4841551e-44], dtype=float32)

**Note:** empty does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [40]:
vec_empty.shape

(5,)

In [41]:
vec_empty[0], vec_empty[3]

(-5407006700.0, 0.0)

### Zero array

In [42]:
vec_zero = np.zeros((5,), dtype=np.float32)

In [43]:
vec_zero

array([0., 0., 0., 0., 0.], dtype=float32)

In [44]:
vec_zero[0], vec_zero[3], vec_zero.shape

(0.0, 0.0, (5,))

### Ones array

In [45]:
vec_ones = np.ones((5,), dtype=np.float32)

In [46]:
vec_ones

array([1., 1., 1., 1., 1.], dtype=float32)

In [47]:
vec_ones[0], vec_ones[1], vec_ones.shape

(1.0, 1.0, (5,))

### arange

`numpy.arange(start, stop, step)`

Like python list range(start, stop, step) but inputs could be **float**. `stop` exlusive.

In [48]:
vec_range = np.arange(1, 11)

In [49]:
vec_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
vec_range = np.arange(1, 11, 2)

In [51]:
vec_range

array([1, 3, 5, 7, 9])

In [52]:
vec_range = np.arange(1, 11, 2.5, dtype=np.float32)

In [53]:
vec_range

array([1. , 3.5, 6. , 8.5], dtype=float32)

**linspace**

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

In [54]:
vec_linsp = np.linspace(
    start=10,
    stop=1000,
    num=100,
)

In [55]:
vec_linsp.shape

(100,)

In [56]:
vec_linsp

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
        100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,  180.,
        190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,
        280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,
        370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,
        460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,
        550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,
        640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,
        730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,
        820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,
        910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,  990.,
       1000.])

**Random**

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [57]:
vec_rand = np.random.rand(10)

In [58]:
vec_rand

array([0.56661556, 0.00551782, 0.90216396, 0.33692306, 0.03666852,
       0.79811012, 0.998831  , 0.37978141, 0.73149699, 0.49837927])

**Note** Right fixing `seed` in jupyter notebook

In [59]:
np.random.seed(10)

np.random.rand(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

In [60]:
np.random.randint(
    low=1,
    high=20,
    size=(5,),
)

array([ 5, 17,  5, 16, 12])

In [61]:
np.random.randint(20, size=(5,))

array([11,  1,  8,  4, 14])

## Conditional selecting

In [62]:
vec = np.array([1, 2, 3, *[4]*3, 5, 6, *[8]*4, 9, 10])

In [63]:
vec

array([ 1,  2,  3,  4,  4,  4,  5,  6,  8,  8,  8,  8,  9, 10])

In [64]:
vec==4

array([False, False, False,  True,  True,  True, False, False, False,
       False, False, False, False, False])

In [65]:
vec[vec == 4]

array([4, 4, 4])

In [66]:
vec[(vec >= 5) & (vec != 8)]

array([ 5,  6,  9, 10])

In [67]:
vec[(vec == 3) | (vec == 10)]

array([ 3, 10])

**`numpy.where`**

In [68]:
np.where(vec == 8)

(array([ 8,  9, 10, 11]),)

In [69]:
vec[np.where(vec == 4)]

array([4, 4, 4])

In [70]:
np.where(vec == 8, vec / 8, vec)

array([ 1.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  1.,  1.,  1.,  1.,  9.,
       10.])

## Basic linear algebra on arrays

In [71]:
vec1 = np.arange(1, 6)
vec2 = np.arange(6, 11)
vec3 = np.ones((5,))

In [72]:
vec1, vec2, vec3

(array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([1., 1., 1., 1., 1.]))

### Sum, mult, div with scalar

In [73]:
vec1 + 5, vec1 - 5

(array([ 6,  7,  8,  9, 10]), array([-4, -3, -2, -1,  0]))

In [74]:
vec3 * 4, 4 * vec3

(array([4., 4., 4., 4., 4.]), array([4., 4., 4., 4., 4.]))

In [75]:
vec3 / 4, vec3 // 4, vec1 % 4

(array([0.25, 0.25, 0.25, 0.25, 0.25]),
 array([0., 0., 0., 0., 0.]),
 array([1, 2, 3, 0, 1]))

### Sum, mult, div with array (element wise)

In [76]:
vec1 + vec3, vec1 - vec3

(array([2., 3., 4., 5., 6.]), array([0., 1., 2., 3., 4.]))

In [77]:
vec1 * vec2, vec1 / vec2

(array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

### Statistical functions

In [78]:
np.sum(vec1), np.mean(vec1), np.median(vec1), np.max(vec1), np.min(vec1), np.std(vec1)

(15, 3.0, 3.0, 5, 1, 1.4142135623730951)

## Задача

Реализуйте скалярное умножение векторов **(5 мин).**

$$<\vec{a},\vec{b}> = \sum_{i=1}^{n}a_{i}b_{i} = a_{1}b_{1}+a_{2}b_{2}+...+a_{n}b_{n}$$

In [79]:
def scalar_mult(a: np.ndarray, b: np.ndarray):
    return np.sum(a*b)

scalar_mult(vec1, vec3), scalar_mult(vec2, vec3), scalar_mult(vec3, vec3)

(15.0, 40.0, 5.0)

In [80]:
# Library function
vec1.dot(vec3), vec2.dot(vec3), vec3.dot(vec3)

(15.0, 40.0, 5.0)

## Задача

Реализуйте $L1, L2$ нормы векторов **(5 мин).**

$$\|\vec{x}\|_{1}=\sum_{i}|x_{i}|$$
$$\|\vec{x}\|_{2}=\sqrt{\sum_{i}|x_{i}|^2}$$

In [81]:
def l_norm(x: np.ndarray, ord: int):
    if ord == 1:
        return np.sum(np.abs(x))
    else:
        return np.sqrt(np.sum(np.abs(x)**2))

In [82]:
l_norm(vec1, ord=1), l_norm(vec1, ord=2)

(15, 7.416198487095663)

In [83]:
# Library function

np.linalg.norm(vec1, ord=1), np.linalg.norm(vec1, ord=2)

(15.0, 7.416198487095663)

## Задача

Реализуйте Евклидово расстояние **(5 мин).**
$$d(\vec{p},\vec{q}) = \sqrt{\sum_{i=1}^{n}(q_{i}-p_{i})^2} = \sqrt{\|\vec{p}\|_{2}^2 + \|\vec{q}\|_{2}^2 - 2<\vec{p},\vec{q}>} = \|p-q\|_{2}$$

Реализуйте косинусное расстояние расстояние **(5 мин).**
$$\cos{(\theta)} = \frac{<\vec{p},\vec{q}>}{\|\vec{p}\|_{2} \|\vec{q}\|_{2}} = \frac{\sum_{i=1}^{n}p_{i}q_{i}}{\sqrt{\sum_{i=1}^{n}|p_{i}|^2}\sqrt{\sum_{i=1}^{n}|q_{i}|^2}}$$

$$d(\vec{p},\vec{q})=1-\cos{(\theta)}$$

In [84]:
def euclidian_distance(p: np.ndarray, q: np.ndarray):
    norm_p_square = l_norm(p, ord=2)
    norm_q_square = l_norm(q, ord=2)
    scalar_pq = scalar_mult(p, q)
    return np.sqrt(norm_p_square**2 + norm_q_square**2 - 2*scalar_pq)

In [85]:
euclidian_distance(vec1, vec2), euclidian_distance(vec1, vec3), euclidian_distance(vec2, vec3)

(11.180339887498949, 5.477225575051661, 15.968719422671311)

In [86]:
def cosine_angle(p: np.ndarray, q: np.ndarray):
    scalar_pq = scalar_mult(p, q)
    norm_p = l_norm(p, ord=2)
    norm_q = l_norm(q, ord=2)
    return scalar_pq / (norm_p*norm_q)

In [87]:
1 - cosine_angle(vec1, vec2), 1 - cosine_angle(vec1, vec3), 1 - cosine_angle(vec2, vec3)

(0.03504949526723289, 0.09546596626670922, 0.015268072165338209)

In [88]:
# Library functions

# Euclidian
np.linalg.norm(vec1 - vec2), np.linalg.norm(vec1 - vec3), np.linalg.norm(vec2 - vec3)

(11.180339887498949, 5.477225575051661, 15.968719422671311)

In [89]:
from scipy.spatial import distance

In [90]:
distance.euclidean(vec1, vec2), distance.euclidean(vec1, vec3), distance.euclidean(vec2, vec3)

(11.180339887498949, 5.477225575051661, 15.968719422671311)

In [91]:
# Cosine
def cosine_lib(p: np.ndarray, q: np.ndarray):
    return p.dot(q) / (np.linalg.norm(p, ord=2) * np.linalg.norm(q, ord=2))

In [92]:
1 - cosine_lib(vec1, vec2), 1 - cosine_lib(vec1, vec3), 1 - cosine_lib(vec2, vec3)

(0.03504949526723289, 0.09546596626670922, 0.015268072165338209)

In [93]:
distance.cosine(vec1, vec2), distance.cosine(vec1, vec3), distance.cosine(vec2, vec3)

(0.03504949526723289, 0.09546596626670911, 0.015268072165338209)

# Matricies

## Create

In [94]:
[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [95]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.arange(1, 13).reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
m1 = np.linspace(1, 12, num=12).reshape((4,3))

In [98]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [99]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.random.seed(1)
np.random.randint(
    low=1,
    high=20,
    size=(4,3),
)

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1],
       [17,  2, 13]])

In [102]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Rank

Метод Гаусса

$$
\quad
\begin{pmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12
\end{pmatrix}
\quad ->
\quad
\begin{pmatrix} 
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & -6 & -12 \\
0 & -9 & -18
\end{pmatrix}
\quad ->
\quad
\begin{pmatrix} 
1 & 2 & 3 \\
0 & -3 & -6
\end{pmatrix}
\quad
$$

**Result:** $rank = 2$

In [104]:
np.linalg.matrix_rank(m1)

2

## Matrix dimensions

In [105]:
m1.shape, len(m1), m1.size, m1.ndim

((4, 3), 4, 12, 2)

## Indexing

`matrix[row_i, col_i]`

or

`matrix[row_i][col_i]`

In [106]:
m1 = np.arange(1, 31).reshape((6, 5))

In [107]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Getting element

In [108]:
m1[3, 0], m1[4, 3]

(16, 24)

In [109]:
m1[3][0], m1[4][3]

(16, 24)

### Getting rows / cols

Rows `matrix[[0,...,n], :]`

Columns `matrix[:, [0,...,m]]`

In [110]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [111]:
m1[1,:], m1[1], m1[1,], m1[1,...]

(array([ 6,  7,  8,  9, 10]),
 array([ 6,  7,  8,  9, 10]),
 array([ 6,  7,  8,  9, 10]),
 array([ 6,  7,  8,  9, 10]))

In [112]:
m1[[1, 3, 5],:]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [113]:
m1[[1, 3, 5]]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [114]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [115]:
m1[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [116]:
m1[:, [2, 4]]

array([[ 3,  5],
       [ 8, 10],
       [13, 15],
       [18, 20],
       [23, 25],
       [28, 30]])

### Putting all together

`matrix[[0,...,n], :][:, [0,...,m]]`

In [117]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [118]:
m1[[1,3,5],:][:,[2,4]]

array([[ 8, 10],
       [18, 20],
       [28, 30]])

### Ranges


**Range rows by index** `matrix[start_index: end_index ,  :]`

**Range columns by index** `matrix[: , start_index: end_index]`

In [119]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [120]:
m1[1:4, :]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [121]:
m1[:, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

### Putting all together

`matrix[start_row_index : end_row_index, start_column_index : end_column_index [, start_column_index : end_column_index]]`

In [122]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [123]:
m1[1:5, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## Stacking vectors / matricies

In [124]:
vec1 = np.arange(1, 6)
vec2 = np.arange(6, 11)

In [125]:
vec1, vec2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [126]:
vec1[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [127]:
vec2[:, np.newaxis]

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [128]:
np.vstack((vec1, vec2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [129]:
np.hstack((vec1[:, np.newaxis], vec2[:, np.newaxis]))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

## Changing values

In [130]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [131]:
m1[1:5, 1:4] = 0

In [132]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16,  0,  0,  0, 20],
       [21,  0,  0,  0, 25],
       [26, 27, 28, 29, 30]])

## Basic linear algebra

### transpose / rotate

In [133]:
m1 = np.arange(1, 31).reshape((6, 5))
m2 = np.eye(5, 6)

In [134]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [135]:
m2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [136]:
m1.T

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [137]:
m1.T.shape

(5, 6)

In [138]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [139]:
np.rot90(m1)

array([[ 5, 10, 15, 20, 25, 30],
       [ 4,  9, 14, 19, 24, 29],
       [ 3,  8, 13, 18, 23, 28],
       [ 2,  7, 12, 17, 22, 27],
       [ 1,  6, 11, 16, 21, 26]])

In [140]:
np.rot90(m1).shape

(5, 6)

In [141]:
m2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [142]:
m2.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [143]:
m1.shape, m2.T.shape

((6, 5), (6, 5))

### Sum, mult, div with scalar

In [144]:
m1 + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [145]:
m1 - 5

array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [146]:
m2 * 4

array([[4., 0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 4., 0.]])

In [147]:
m2 / 4

array([[0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.  ]])

In [148]:
m2 // 4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [149]:
m1 % 6

array([[1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4],
       [5, 0, 1, 2, 3],
       [4, 5, 0, 1, 2],
       [3, 4, 5, 0, 1],
       [2, 3, 4, 5, 0]])

### Sum, mult, div with matrix (element wise)

In [150]:
m1 + m2.T

array([[ 2.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10.],
       [11., 12., 14., 14., 15.],
       [16., 17., 18., 20., 20.],
       [21., 22., 23., 24., 26.],
       [26., 27., 28., 29., 30.]])

In [151]:
m1 - m2.T

array([[ 0.,  2.,  3.,  4.,  5.],
       [ 6.,  6.,  8.,  9., 10.],
       [11., 12., 12., 14., 15.],
       [16., 17., 18., 18., 20.],
       [21., 22., 23., 24., 24.],
       [26., 27., 28., 29., 30.]])

In [152]:
m1 * m2.T

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.],
       [ 0.,  0.,  0., 19.,  0.],
       [ 0.,  0.,  0.,  0., 25.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [153]:
m1 / (np.ones(m1.shape)*2)

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5],
       [13. , 13.5, 14. , 14.5, 15. ]])

In [154]:
m1 // (np.ones(m1.shape)*2)

array([[ 0.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.],
       [ 5.,  6.,  6.,  7.,  7.],
       [ 8.,  8.,  9.,  9., 10.],
       [10., 11., 11., 12., 12.],
       [13., 13., 14., 14., 15.]])

In [155]:
m1 % (np.ones(m1.shape)*6)

array([[1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4.],
       [5., 0., 1., 2., 3.],
       [4., 5., 0., 1., 2.],
       [3., 4., 5., 0., 1.],
       [2., 3., 4., 5., 0.]])

### Matrix product

In [156]:
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [157]:
m2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [158]:
m1.shape, m2.shape

((6, 5), (5, 6))

In [159]:
m1 @ m2

array([[ 1.,  2.,  3.,  4.,  5.,  0.],
       [ 6.,  7.,  8.,  9., 10.,  0.],
       [11., 12., 13., 14., 15.,  0.],
       [16., 17., 18., 19., 20.,  0.],
       [21., 22., 23., 24., 25.,  0.],
       [26., 27., 28., 29., 30.,  0.]])

In [160]:
m1.dot(m2)

array([[ 1.,  2.,  3.,  4.,  5.,  0.],
       [ 6.,  7.,  8.,  9., 10.,  0.],
       [11., 12., 13., 14., 15.,  0.],
       [16., 17., 18., 19., 20.,  0.],
       [21., 22., 23., 24., 25.,  0.],
       [26., 27., 28., 29., 30.,  0.]])